teamtnt/tntsearch

.idea/vcs.xml
Doesn't need to be versioned :)
Great project btw.
Cheers from Toptal :beers:
=> Removing .idea directory

src/Stemmer/PorterStemmer.php
@nticaric requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/teamtnt/tntsearch/
=> Scrutinizer Auto-Fixes

helper/helpers.php
As discussed in https://github.com/teamtnt/tntsearch/issues/36
=> Remove dd function

tests/TNTSearchTest.php
Added fuzzy search unit test, in case when multiple words are found.
=> Added unit test

src/Stemmer/ItalianStemmer.php
Created Italian Stemmer based on the original version written by Roberto Mirizzi
=> Created Italian Stemmer

README.md
Make the markdown headers correct
=> Update to headers

src/Indexer/TNTIndexer.php, src/Support/Collection.php, src/Support/Highlighter.php, src/TNTSearch.php
Add some basical php-doc.
RomanSh
=> Add some basical php-doc.

src/Stemmer/PortugueseStemmer.php, tests/stemmer/PortugueseStemmerTest.php
Added Portuguese Stemmer and Portuguese Stemmer Test.
=> Added Portuguese Stemmer

src/TNTSearch.php
=> fix isFileSystemIndex()

src/Support/Highlighter.php
It was missing a space between the tag and the first attribute added to it.
=> Insert a space between the tag and the first attribute.

src/FileReaders/TextFileReader.php, src/Indexer/TNTIndexer.php
See #150 for example usage (prevent indexing of the file path or restrict to only a part of the path).
=> implements #150: ability to filter and/or map the file Collection before processing the documents

README.md
Clarity, spelling, grammar and remove duplication. Also, better use of punctuation. And a call to contribute.
=> Revamp readme

src/Stemmer/ItalianStemmer.php
I fixed some deprecations on Italian Stemmer  Class
=> Italian Stemmer patch

src/Connectors/Connector.php, src/Connectors/MySqlConnector.php
=> Use class constant in MySqlConnector class.

src/Classifier/TNTClassifier.php, src/Indexer/TNTIndexer.php
This patch makes TNTSearch API behaviour consistent with changes in  b675c625782b20563e4b01bf7c2934b701b80489
=> Change default stemmer in indexer and classifier too

src/Stemmer/FrenchStemmer.php, tests/stemmer/FrenchStemmerTest.php
=> Add french Stemmer

src/Stemmer/PolishStemmer.php, tests/stemmer/PolishStemmerTest.php
This PR adds simple stemmer for Polish language. I'm no linguist so I've been looking for some FOSS stemmer to port. The final choice was [pl_stemmer](https://github.com/Tutanchamon/pl_stemmer) by Błażej Kubiński (MIT).
The stemmer is not perfect, but fully fledged stemmers covering Polish language complexities are rather huge, and theirs impact on the performance would be not negligible. They are rather suited for offline processing.
IMO, this stemmer is a good trade off/starting point, and I'm planning to use it in my service.
=> Polish stemmer

src/Support/Collection.php
This PR fixes PHP 8.1 incompatibilities. Let me know if there are any questions or concerns. Thank you 🙏
=> PHP 8.1: Fix incompatible methods

src/Indexer/TNTIndexer.php
Fixes https://github.com/teamtnt/tntsearch/issues/60
=> Total documents count fix

src/Indexer/TNTGeoIndexer.php
override insert and delete functions to allow insert and update documents in TNTGeoIndexer
Linked to this issues : #276
=> Allow insert and update document with TNTGeoSearch

src/Indexer/TNTGeoIndexer.php
sorry, I forgot to add the use of the Collection
=> fix missing use

src/Support/NGramTokenizer.php
=> mb_strlen in NGramTokenizer

src/Support/EdgeNgramTokenizer.php
fixed EdgeNgramTokenizer split word count
=> fixed EdgeNgramTokenizer split word count

src/Connectors/OracleDBConnector.php, src/Engines/EngineTrait.php
Added OracleDB Connector.
Needed Indexing from OracleDB Database
=> Add OracleDB Connector

src/Engines/MysqlEngine.php, src/Engines/SqliteEngine.php
Allow `info` table to contain string values
=> Fixes #329

composer.json, src/Classifier/TNTClassifier.php, src/Connectors/Connector.php, src/Connectors/ConnectorInterface.php, src/Connectors/FileSystemConnector.php, src/Contracts/EngineContract.php, src/Engines/EngineTrait.php, src/Engines/MysqlEngine.php, src/Engines/RedisEngine.php, src/Engines/SqliteEngine.php, src/Indexer/TNTGeoIndexer.php, src/Indexer/TNTIndexer.php, src/KeywordExtraction/Rake.php, src/Spell/JaroWinklerDistance.php, src/Support/Collection.php, src/Support/Highlighter.php, src/TNTFuzzyMatch.php, src/TNTGeoSearch.php, src/TNTSearch.php
I did add a lot of types for most functions / methods but I'm not 100% sure if everything is correct. Maybe @nticaric could check some of them?
Sadly I was not able to execute the 'Redis' tests - maybe some new tests (for `MysqlEngine` and `SqliteEngine`) could be added?
I also added `ext-pdo` as required extension. It seems to me as if it is always necessary 🤔 Please correct me if that's wrong.
There are also some code-style updates (according to PSR-2)
=> fixes teamtnt/tntsearch#333

src/Engines/EngineTrait.php, src/Engines/MysqlEngine.php, src/Engines/SqliteEngine.php, src/Exceptions/InvalidEngineException.php, src/TNTSearch.php
Hello,
I created a small fix for the case that the given Engine, Stemmer or Tokenizer are not compatible due to mismatching interface or simply "not existing"
=> fixes teamtnt/tntsearch #339 #322

README.md
Hello @nticaric 
here I updated the PHP requirement to >= 7.4 in the README file.
I forgot to do so in #345 - noted by @felipeabranches in #344
=> Update PHP requirement in README to >= 7.4
