teamtnt/tntsearch

src/TNTSearch.php

Don't search only for the first word if fuzziness is enabled. Main method refactored into two private methods.

Search for all keywords and documents if fuzziness is enabled

---

src/TNTSearchServiceProvider.php

As of laravel 5.4 share has been removed. You will have to use the singleton instead.

fix for laravel 5.4

---

src/TNTGeoSearch.php

The earlier array key was "execution time" with space between which is not recommended.

execution_time key properly named for convenient usage

---

src/Indexer/TNTIndexer.php

This PR fixes PHP 7.2 sqlite3 bug then `SQLSTATE[HY000]: General error: 21 bad parameter or other API misuse` error message is shown.
SQL Statements must be refreshed/reset after error was handled.
This also fixes: 
https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/129
https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/127

Reset index statements after error was catched

---

src/Support/Highlighter.php

This branch allows you to specify attributes to be added to the tag used to highlight search terms. So besides the tag to be used (`<em>` by default) you can specify attributes like` class="term"`, `title="You searched for this."` or `style="color: red;"` all in array format, where the key is the attribute name and the value is the attribute value.

New feature: It's possible to add attributes to the highlighter tag.

---

src/TNTSearch.php

I followed your tutorial here http://tnt.studio/blog/did-you-mean-functionality-with-laravel-scout where you explain how to create trigrams.
If the function `createIndex` is called there is no way to disable the ouput of the `TNTINdexer`.
This is suboptimal if you have an api whereof you can create posts or sth. else and run the trigram generator directly after the creation process.
With this little it's possible to control this behavior.

Disable output on createIndex

---

src/Indexer/TNTIndexer.php

Hi,
I am using TNTSearch Driver for Laravel Scout with a custom Laravel database driver. TNTSearchScoutServiceProvider calls TNTSearch::setDatabaseHandle() and passes my custom PDO driver but TNTIndexer still tries to create a connector (which it would never use) and fails with an unsupported driver exception.
Thank you for your consideration.

Don't create connector if connection already exists

---

src/Indexer/TNTIndexer.php

This extends the `TNTIndexer` 'extension' option so that it can be a callable that returns a Boolean value or an array of extensions, or a string as before. This allows for indexing of several different file types at once.
For example, to index .html and .json files, either of these approaches could be taken:
```
$config = [
...
"extension" => array('html','json'),
...
];
$tnt->loadConfig($config);
```
OR
```
$config = [
...
"extension" => function($object) {
return in_array($object->getExtension(), array('json', 'html'));
},
...
];
$tnt->loadConfig($config);
```
The callable approach allows for very flexible filtering, excluding specific subdirs or files that match the extension but should be excluded when matching a given RegEx for example.
In order to handle file contents by file type, …

feature: TNTIndexer 'extension' option as array or callable

---

src/Support/Collection.php
src/TNTSearch.php
tests/TNTSearchTest.php

This PR allows to configure the stemmer by setting a stemmer class in the `$config`. It also adds two new collection methods to clean up the `TNTSearch` code slightly.
Not sure if this has been attempted before, but I figured it would make sense to have a configurable stemmer if there are several to choose from. Or is there another way to configure the stemmer?

Code quality improvement + configurable stemmer

---

src/TNTSearch.php

See https://github.com/teamtnt/tntsearch/issues/163 for further information for this fix.
If condition was moved in commit 40c4395cf04e089b6f2fd4dd98d4b1d09de1ce6b. But this causes a problem. Could be because function is called multiple times during one search.

PR: reverts position of if condition made with older commit

---

src/Indexer/TNTIndexer.php

In pull request #151 a couple implicitly required properties were introduced to the `FileReaderInterface`: the `fileMapCallback` and `fileFilterCallback`.
For users creating their own implementation of the `FileReaderInterface`, if these properties don't exist a notice-level error is issued when `is_callable` is applied to them. In environments were all errors are upgraded to `ErrorException` this causes breakages.
Since PHP doesn't allow for properties to be defined by interfaces, I think the only way to handle this is to use `property_exists` before `is_callable`.
Here's a failing test case this PR addresses:
```php
<?php
include 'vendor/autoload.php';
use TeamTNT\TNTSearch\TNTSearch;
use TeamTNT\TNTSearch\FileReaders\FileReaderInterface;
error_reporting(-1);
set_error_handler(function …
```

Check FileReader properties exist before accessing

---

src/Indexer/TNTIndexer.php

While indexing my records through laravel scout commands I noticed, that the time it took to update records in the index changed linearly with the number of records that were already in the database, making indexing slower and slower. (Note: I am not using tntsearches indexing command, because I am also indexing relationships)
I tracked this down to the 2 queries on `doclist` in `TNTIndexer::delete` which took a while since they filtered for a column without an index on it. This leads the db to actually scan all records. Adding an index makes it more constant (-ish).
In theory, adding an index should impact insertion time a bit, but in my testing I found that this was offset by the time saved in the deletion queries very fast.
---
Here is the difference in indexing 20k records before and …

Add index for doc_id

---

src/Support/Tokenizer.php
tests/support/TokenizerTest.php

I would like to propose improvements to the default TNTSearch Tokenizer. I've always felt that TNTSearch produces "unexpected" results from the user standpoint, especially when searching for more complex word forms in large text blocks. At first I thought improving ProductTokenizer by alternatively splitting by "/[\s,.:;"']/", but even this simple regex doesn't cover most common cases, hence my suggestion to enhance the default tokenizer.
This patch adds Unicode groups for dashes and connectors to the ignore list of split characters since they are mostly used inside words, not as word spliting characters. This enables searching for product models, SKU or UUID numbers, dates in their short form, function/constant names in programming manuals, etc.
While at it, also add @ character to the …

Enhance default tokenizer.

---

src/Support/Expression.php
tests/support/ExpressionTest.php

This patch changes two things:
1) When using custom Tokenizer, enables searching for UUIDs, product names and other items with dashes in their names by counting only space and dash character as an expression instead of just dash (see:
https://github.com/teamtnt/tntsearch/issues/161, https://github.com/teamtnt/tntsearch/issues/215, https://github.com/trilbymedia/grav-plugin-tntsearch/issues/92)
2) In some sense it partially reverts https://github.com/teamtnt/tntsearch/commit/33cc5244f02592e53ceffacf3c366e0b5111d7e8 as email address parts are broken into tokens in the default Tokenizer anyway.
P.S. Negative boolean search is still completely broken. It errors out on more than one negative expression ('searchstring -test -test2') and it returns incorrect results with one negative expression …

Enhance boolean search expression.

---

README.md
src/Support/AbstractTokenizer.php
src/Support/Highlighter.php
src/Support/ProductTokenizer.php
src/Support/Tokenizer.php
src/Support/TokenizerInterface.php
src/TNTSearch.php
tests/indexer/TNTIndexerTest.php

This change makes highlighter word splitting pattern inline with what is used in the loaded tokenizer.
In order to take advantage of this tokenizers now should extend AbstractTokenizer class and define splitting pattern value in $pattern static protected variable.
I was not sure if this is the best way to do this, but I've tried to keep backward compatibility with possible custom tokenizers as much as possible. Most difficult question was if it is OK to modify TokenizerInterface by making getPattern() required. If we don't add it, the code which relies on custom tokenizers and uses Highlight class directly will fail with unknown method error. If we add it, at least Exception is thrown that tokenizer implementation needs to be adjusted according to interface specification.
Comments are …

Make highlighter use splitting pattern of the tokenizer

---

src/Indexer/TNTIndexer.php

I am using Laravel Scout driver and due to WAL enabled by default its breaking my entire application which is production currently. 
Thus, Making WAL to be enabled via config to give more flexibility to the users and prevent form unexpected errors

Enable wal via config

---

.travis.yml
composer.json

This PR attempts to add support for the recently-released PHP 8, so that e.g., it can be upgraded along with Laravel Scout.

Add PHP 8 support

---

src/Support/ProductTokenizer.php
tests/stemmer/GermanStemmerTest.php
tests/stemmer/PorterStemmerTest.php
tests/stemmer/PortugueseStemmerTest.php

Final patch this week - fixes deprecated warnings and adds period to the ProductTokenizer to pass the tests.
The only failing test now is TNTSearchTest::testSearchBoolean. Boolean search is completely broken probably because of this change https://github.com/teamtnt/tntsearch/commit/f2df690474e66af8b46a56723e07e9a4b2c4b6a9  I will try to investigate it next week.

Make PHPUnit happier

---

src/Support/Expression.php
tests/support/ExpressionTest.php

If search query didn't contain opening parentheses this while loop produced memory exhausted errors.
Not sure if this a right way to fix this, but if stack is empty or have reached the end array_pop should return null.
Also, add some tests to catch these cases.

Fix infinite loop in search expression

---

src/TNTSearch.php

In order to make it possible to rank different laravel models by score, we'll need the docScores to make use in it in the laravel provider plugin (see pr: https://github.com/teamtnt/laravel-scout-tntsearch-driver/pull/344)
#55
https://github.com/teamtnt/laravel-scout-tntsearch-driver/pull/344
https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/222

:sparkles: Introducing ability to make docScores available outside of TNTSearch

---

src/TNTSearch.php
tests/TNTSearchTest.php

Currently, if FuzzySearch is enabled and the search term is an exact match it will only return the exact match and not attempt to do a fuzzy search. This change simply adds a flag that gives the developers the choice to return multiple results even on a direct match by running the fuzzySearch (if fuzziness is enabled).
This seems to have been attempted in a previous [issue](https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/172) but was subsequently rolled back #168  as people had complained about a reduction in search quality #163  . From what I gather the reason for the poor performance was due to search always returning the fuzzy match results over the exact match as most would have expected. This pr aims to keeps all logic as is unless the flag is set, only then should …

Flag to return all FuzzySearch results on exact match

---

src/Connectors/SQLiteConnector.php

#281 Update SQLiteConnector to avoid depreciation : Using ${var} in strings is deprecated, use {$var} instead in PHP 8.2

Update SQLiteConnector to avoid depreciation on string with PHP 8.2

---

README.md

I noticed an issue in the readme file where the example for fuzziness was incorrect. It incorrectly sets the "fuzziness" attribute, which doesn't exist. Instead, it should call the "fuzziness" method.
❌ `$tnt->fuzziness = true;`
✅ `$tnt->fuzziness(true);`
This pull request (PR) corrects the example by using the appropriate methods.
Resolved: https://github.com/teamtnt/tntsearch/issues/300

docs: fix fuzziness method example

---

src/Engines/MysqlEngine.php

This PR adds support for MySQL as engine.
Features:
- indexing is much faster than with SqliteEngine as it uses multi-insert statements (`INSERT INTO (...) VALUES (1,1,1), (1,1,2), ...`)
- index name gets used as table name prefix, so you can use an existing MySQL database
- database credentials can be entered via 
```
'engine' => MysqlEngine::class,
'mysql_host' => $dbParams['host'],
'mysql_database' => $dbParams['dbname'],
'mysql_user' => $dbParams['user'],
'mysql_password' => $dbParams['password']
```

Add MySQL engine

---

src/Engines/MysqlEngine.php

Currently there is this index:
https://github.com/teamtnt/tntsearch/blob/a763e66ca1bdebf1fab8f9ed10ec4bdbe2682bb0/src/Engines/MysqlEngine.php#L74
For retrieving all documents for a certain term the following query gets used:
https://github.com/teamtnt/tntsearch/blob/a763e66ca1bdebf1fab8f9ed10ec4bdbe2682bb0/src/Engines/MysqlEngine.php#L385
With the current index, this needs to sort the results with `filesort`:
When we also add `hit_count` to the index, the `filesort` is not necessary anymore but filtering and sorting gets fully covered by the index:
This results in better performance.
There is no drawback for other queries which only filter by `term_id` as MySQL in this case can also use the index prefix (in this case only the column `term_id`).

[MySQL engine ] Add hit_count to doclist database index

---

src/Engines/MysqlEngine.php

Compare with Sqlite approach:
https://github.com/teamtnt/tntsearch/blob/069e63e377da578ddf8b9524dd97e463499150b3/src/Engines/SqliteEngine.php#L225
Currently `num_docs` and `num_hits` are overwritten with every update.

[MySQL engine] Update for wordlist overwrote num_docs + num_hits instead of adding to previous value

---

composer.json

After #316 brought support for MySQL, the `SQlite` PHP extension became optional.
Btw: When will there be a released tag / version based on current `master` branch`?

Remove sqlite PHP extension as it is only an optional dependency nowadays

---

src/Support/Collection.php

PHP have deprecated the implicit nullable parameter for functions. 
The ?callable explicitly marks the $callback parameter as nullable. This change ensures compatibility with newer PHP versions while keeping the functionality the same.

Explicitly declare parameter as nullable

---

src/Engines/MysqlEngine.php

This pull request relates to issue #327 
It solves an issue when using `searchBoolean()` with the `MysqlEngine` - previously the `doclist` table was not properly prefixed, resulting in an error:
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.doclist' doesn't exist
```

Use properly prefixed 'doclist' table

---

src/Engines/MysqlEngine.php

Remove redundant configuration values:
- mysql_database
- mysql_host
- mysql_user
- mysql_password
Simply use the same values as other engines / connectors:
- host
- database
- username
- password

fixes teamtnt/tntsearch#332

---

src/Engines/RedisEngine.php
src/Engines/SqliteEngine.php

Hello,
this is just a very small PR to add an additional `info` after the index loop to clear up that all given rows have been processed. See discussion in https://github.com/teamtnt/tntsearch/issues/312

Add additional 'Processed x rows' after the loop, fixed #312

---

src/Engines/MysqlEngine.php

Hello,
while working on improved types (regarding PHP 7.4 & 8+) I overlooked this issue - we need to check if the variable is set rather than checking the content.
By checking the value the logic will evaluate and throw
```
Uncaught Error: Typed property TeamTNT\TNTSearch\Engines\SqliteEngine::$index must not be accessed before initialization in
```

Fix 'MysqlEngine->selectIndex()' when index has not been set previously

---

src/Engines/EngineTrait.php

Hello,
here we create a `mariadb` driver alias which uses the `MySqlConnector` internally.
Best regards

Create 'mariadb' alias refs #349
